const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/pedidosSubalmacen.controller');
const { authenticate, authorize } = require('../middleware/auth');
router.use(authenticate);
router.get('/', ctrl.getAll);
router.get('/:id', ctrl.getById);
router.post('/', authorize('Administrador','Responsable de Servicio'), ctrl.create);
router.put('/:id/atender', authorize('Administrador','Suministrador'), ctrl.atender);
router.put('/:id/cancelar', ctrl.cancelar);
module.exports = router;
